version: "3"

services:
  postgresql:
    image: postgres
    restart: always
    container_name: rumbl_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rumbl_dev
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
